<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClubSpot.SharedKernel\ClubSpot.SharedKernel.csproj" />
    <ProjectReference Include="..\ClubSpot.Modules.Clubes\ClubSpot.Modules.Clubes.csproj" />
    <ProjectReference Include="..\ClubSpot.Modules.Reservas\ClubSpot.Modules.Reservas.csproj" />
    <ProjectReference Include="..\ClubSpot.Modules.Padel\ClubSpot.Modules.Padel.csproj" />
    <ProjectReference Include="..\ClubSpot.Modules.Futbol\ClubSpot.Modules.Futbol.csproj" />
    <ProjectReference Include="..\ClubSpot.Modules.Finanzas\ClubSpot.Modules.Finanzas.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
