// <auto-generated />
using System;
using System.Collections.Generic;
using ClubSpot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubSpot.Infrastructure.Persistence.Migrations.Core
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260816013129_InitialCore")]
    partial class InitialCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubSpot.Domain.Core.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("DepositPercent")
                        .HasColumnType("integer")
                        .HasColumnName("depositPercent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timeZone");

                    b.Property<string>("Venue")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uxClubSlug");

                    b.ToTable("club", "core", t =>
                        {
                            t.HasCheckConstraint("ckClubDepositPercent", "\"depositPercent\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("clubId");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("moduleId");

                    b.Property<DateTimeOffset>("ContractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contractedAt");

                    b.HasKey("TenantId", "ModuleId");

                    b.HasIndex("TenantId");

                    b.ToTable("clubModule", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorUserId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PersonId", "CreatedAt");

                    b.ToTable("personNote", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isBlocked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneDigits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phoneDigits");

                    b.Property<string>("PreferredSport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferredSport");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("searchName");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Debt", "ClubSpot.Domain.Core.People.Person.Debt#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("debtAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("debtCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PhoneDigits")
                        .HasDatabaseName("ixPersonTenantPhoneDigits");

                    b.HasIndex("TenantId", "SearchName")
                        .HasDatabaseName("ixPersonTenantSearchName");

                    b.ToTable("person", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordHash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uxUserTenantEmail");

                    b.ToTable("user", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.HasOne("ClubSpot.Domain.Core.Club", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Note", b =>
                {
                    b.HasOne("ClubSpot.Domain.Core.People.Person", null)
                        .WithMany("Notes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.OwnsMany("ClubSpot.Domain.Core.UserRole", "UserRoles", b1 =>
                        {
                            b1.Property<Guid>("userId")
                                .HasColumnType("uuid")
                                .HasColumnName("userId");

                            b1.Property<string>("Role")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("role");

                            b1.HasKey("userId", "Role");

                            b1.ToTable("userRole", "core");

                            b1.WithOwner()
                                .HasForeignKey("userId");
                        });

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Person", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
