// <auto-generated />
using System;
using ClubSpot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubSpot.Infrastructure.Persistence.Migrations.Core
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubSpot.Domain.Core.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("DepositPercent")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("time_zone");

                    b.Property<string>("Venue")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_club_slug");

                    b.ToTable("club", "core", t =>
                        {
                            t.HasCheckConstraint("ck_club_deposit_percent", "deposit_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("module_id");

                    b.Property<DateTimeOffset>("ContractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contracted_at");

                    b.HasKey("TenantId", "ModuleId");

                    b.HasIndex("TenantId");

                    b.ToTable("club_module", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_user_tenant_email");

                    b.ToTable("user", "core");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.HasOne("ClubSpot.Domain.Core.Club", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.OwnsMany("ClubSpot.Domain.Core.UserRole", "UserRoles", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<string>("Role")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("role");

                            b1.HasKey("user_id", "Role");

                            b1.ToTable("user_role", "core");

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
