// <auto-generated />
using System;
using System.Collections.Generic;
using ClubSpot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubSpot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClubSpotDbContext))]
    [Migration("20260820030551_UserEmailGlobalUnique")]
    partial class UserEmailGlobalUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubSpot.Domain.Bookings.AvailabilityOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("courtId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("Windows")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("windows");

                    b.HasKey("Id")
                        .HasName("pkAvailabilityOverrides");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("ixAvailabilityOverridesCourtId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixAvailabilityOverridesTenantId");

                    b.ToTable("availabilityOverrides", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.AvailabilityOverrideDate", b =>
                {
                    b.Property<Guid>("OverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("overrideId");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.HasKey("OverrideId", "Date")
                        .HasName("pkAvailabilityOverrideDates");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixAvailabilityOverrideDatesTenantId");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ixAvailabilityOverrideDatesTenantIdDate");

                    b.ToTable("availabilityOverrideDates", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancellationReason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelledAt");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("courtId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("customerName");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("customerPhone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationMinutes");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paymentMode");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer")
                        .HasColumnName("startMinute");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ClubSpot.Domain.Bookings.Booking.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("priceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("priceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pkBookings");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ixBookingsPersonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixBookingsTenantId");

                    b.HasIndex("CourtId", "Date")
                        .HasDatabaseName("ixBookingsCourtIdDate");

                    b.HasIndex("TenantId", "Date")
                        .HasDatabaseName("ixBookingsTenantIdDate");

                    b.ToTable("bookings", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.BookingCheckout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingId");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issuedAt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ClubSpot.Domain.Bookings.BookingCheckout.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pkBookingCheckouts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixBookingCheckoutsTenantId");

                    b.HasIndex("BookingId", "IssuedAt")
                        .HasDatabaseName("ixBookingCheckoutsBookingIdIssuedAt");

                    b.ToTable("bookingCheckouts", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detail");

                    b.PrimitiveCollection<int[]>("Durations")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("durations");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("boolean")
                        .HasColumnName("isCovered");

                    b.Property<int>("MinimumNoticeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimumNoticeMinutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("NightStartsAtMinute")
                        .HasColumnType("integer")
                        .HasColumnName("nightStartsAtMinute");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduleId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport");

                    b.Property<int>("StartIncrementMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("startIncrementMinutes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DayPrice", "ClubSpot.Domain.Bookings.Court.DayPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("dayPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("dayPriceCurrency")
                                .IsFixedLength();
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NightPrice", "ClubSpot.Domain.Bookings.Court.NightPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("nightPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("nightPriceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pkCourts");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ixCourtsScheduleId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixCourtsTenantId");

                    b.HasIndex("TenantId", "Sport", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uxCourtsTenantIdSportSortOrder");

                    b.ToTable("courts", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("externalId");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("OrphanReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("orphanReason");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Rail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rail");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ClubSpot.Domain.Bookings.Payment.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("currency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pkPayments");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ixPaymentsBookingId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixPaymentsTenantId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uxPaymentsProviderExternalId");

                    b.ToTable("payments", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("WeeklyRanges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weeklyRanges");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pkSchedules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixSchedulesTenantId");

                    b.ToTable("schedules", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.Activity.ActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actorName");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actorUserId");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("bookingId");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredAt");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("paymentId");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pkActivityLogEntries");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixActivityLogEntriesTenantId");

                    b.HasIndex("TenantId", "BookingId")
                        .HasDatabaseName("ixActivityLogEntriesTenantIdBookingId");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ixActivityLogEntriesTenantIdOccurredAt");

                    b.HasIndex("TenantId", "PersonId")
                        .HasDatabaseName("ixActivityLogEntriesTenantIdPersonId");

                    b.ToTable("activityLogEntries", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("DepositPercent")
                        .HasColumnType("integer")
                        .HasColumnName("depositPercent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timeZone");

                    b.Property<string>("Venue")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("venue");

                    b.HasKey("Id")
                        .HasName("pkClubs");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uxClubsSlug");

                    b.ToTable("clubs", "public", t =>
                        {
                            t.HasCheckConstraint("ckClubsDepositPercent", "\"depositPercent\" IN (50, 100)");
                        });
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("clubId");

                    b.Property<string>("ModuleId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("moduleId");

                    b.Property<DateTimeOffset>("ContractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contractedAt");

                    b.HasKey("TenantId", "ModuleId")
                        .HasName("pkClubModules");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixClubModulesClubId");

                    b.ToTable("clubModules", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorUserId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("personId");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pkPersonNotes");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ixPersonNotesPersonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixPersonNotesTenantId");

                    b.HasIndex("TenantId", "PersonId", "CreatedAt")
                        .HasDatabaseName("ixPersonNotesTenantIdPersonIdCreatedAt");

                    b.ToTable("personNotes", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("createdBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isBlocked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneDigits")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phoneDigits");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("searchName");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Debt", "ClubSpot.Domain.Core.People.Person.Debt#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("debtAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("debtCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id")
                        .HasName("pkPeople");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixPeopleTenantId");

                    b.HasIndex("TenantId", "PhoneDigits")
                        .HasDatabaseName("ixPeopleTenantIdPhoneDigits");

                    b.HasIndex("TenantId", "SearchName")
                        .HasDatabaseName("ixPeopleTenantIdSearchName");

                    b.ToTable("people", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passwordHash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.HasKey("Id")
                        .HasName("pkUsers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uxUsersEmail");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ixUsersTenantId");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.AvailabilityOverride", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fkAvailabilityOverridesCourtId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.AvailabilityOverrideDate", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.AvailabilityOverride", null)
                        .WithMany("Dates")
                        .HasForeignKey("OverrideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fkAvailabilityOverrideDatesOverrideId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkBookingsCourtId");

                    b.HasOne("ClubSpot.Domain.Core.People.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fkBookingsPersonId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.BookingCheckout", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkBookingCheckoutsBookingId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Court", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Schedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkCourtsScheduleId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Payment", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkPaymentsBookingId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.ClubModule", b =>
                {
                    b.HasOne("ClubSpot.Domain.Core.Club", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fkClubModulesClubId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Note", b =>
                {
                    b.HasOne("ClubSpot.Domain.Core.People.Person", null)
                        .WithMany("Notes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fkPersonNotesPersonId");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.User", b =>
                {
                    b.OwnsMany("ClubSpot.Domain.Core.UserRole", "UserRoles", b1 =>
                        {
                            b1.Property<Guid>("userId")
                                .HasColumnType("uuid")
                                .HasColumnName("userId");

                            b1.Property<string>("Role")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("role");

                            b1.HasKey("userId", "Role")
                                .HasName("pkUserRoles");

                            b1.ToTable("userRoles", "public");

                            b1.WithOwner()
                                .HasForeignKey("userId")
                                .HasConstraintName("fkUserRolesUserId");
                        });

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.AvailabilityOverride", b =>
                {
                    b.Navigation("Dates");
                });

            modelBuilder.Entity("ClubSpot.Domain.Core.People.Person", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
