// <auto-generated />
using System;
using ClubSpot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClubSpot.Infrastructure.Persistence.Migrations.Bookings
{
    [DbContext(typeof(BookingsDbContext))]
    partial class BookingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookings")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DayPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("dayPrice");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detail");

                    b.PrimitiveCollection<int[]>("Durations")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("durations");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("boolean")
                        .HasColumnName("isCovered");

                    b.Property<int>("MinimumNoticeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("minimumNoticeMinutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("NightPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("nightPrice");

                    b.Property<int>("NightStartsAtMinute")
                        .HasColumnType("integer")
                        .HasColumnName("nightStartsAtMinute");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduleId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortOrder");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport");

                    b.Property<int>("StartIncrementMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("startIncrementMinutes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Sport", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("uxCourtTenantSportSortOrder");

                    b.ToTable("court", "bookings");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("SpecialDates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialDates");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantId");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timeZone");

                    b.Property<string>("WeeklyRanges")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weeklyRanges");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("schedule", "bookings");
                });

            modelBuilder.Entity("ClubSpot.Domain.Bookings.Court", b =>
                {
                    b.HasOne("ClubSpot.Domain.Bookings.Schedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
